// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiovixlsqdqglubctdzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpb3ZpeGxzcWRxZ2x1YmN0ZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDgzNjIsImV4cCI6MjA2NDUyNDM2Mn0.JbCPQiK3a5AwGLb0uYQz87a7R5-RezqEME6Mg5OqPPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);